[install] modify and regenerate the acceptance tests after linking 'ln -sf ../../MG5aMC_PLUGIN/CUDACPP_OUTPUT PLUGIN/CUDACPP_OUTPUT'
PS: acceptance tests now succeed in the CI - however, will revert because adding back a symlink in PLUGIN/CUDACPP_OUTPUT should be avoided

(NB it is not enough to copy or symlink test_simd_madevent.py, because acceptance tests need the code generation plugin)

diff --git a/.github/workflows/madgraph_launch_test.yml b/.github/workflows/madgraph_launch_test.yml
--- a/.github/workflows/madgraph_launch_test.yml
+++ b/.github/workflows/madgraph_launch_test.yml
@@ -49,9 +49,13 @@ jobs:
             cd MG5aMC/mg5amcnlo/
             cp input/.mg5_configuration_default.txt input/mg5_configuration.txt
             cp Template/LO/Source/.make_opts Template/LO/Source/make_opts
-            rm -f cudacpp_acceptance_tests
-            ln -sf ../MG5aMC_PLUGIN/CUDACPP_OUTPUT/acceptance_tests cudacpp_acceptance_tests # workaround for 'relative position not supported'
-            ./tests/test_manager.py -p./cudacpp_acceptance_tests/ test_simd_cpp_eemumua_float 
+            # *** NB1: acceptance tests require code generation (so in principle both PLUGIN and ../MG5aMC_PLUGIN are an option) 
+            # *** NB2: test_manager.py cannot handle absolute paths and '..' relative paths (therefore ../MG5aMC_PLUGIN will not work)
+            # *** ===> therefore, the only option is to install CUDACPP_OUTPUT in PLUGIN (this is done and undone in each CI job) 
+            if [ -f PLUGIN/CUDACPP_OUTPUT ]; then echo 'ERROR! PLUGIN/CUDACPP_OUTPUT already exists'; exit 1; fi
+            ln -sf ../../MG5aMC_PLUGIN/CUDACPP_OUTPUT PLUGIN/CUDACPP_OUTPUT
+            ./tests/test_manager.py -p./PLUGIN/CUDACPP_OUTPUT/acceptance_tests/ test_simd_cpp_eemumua_float 
+            rm -f PLUGIN/CUDACPP_OUTPUT
 
   simd_cpp_heft_ggh_double:
     # The type of runner that the job will run on
@@ -71,9 +75,13 @@ jobs:
             cd MG5aMC/mg5amcnlo/
             cp input/.mg5_configuration_default.txt input/mg5_configuration.txt
             cp Template/LO/Source/.make_opts Template/LO/Source/make_opts
-            rm -f cudacpp_acceptance_tests
-            ln -sf ../MG5aMC_PLUGIN/CUDACPP_OUTPUT/acceptance_tests cudacpp_acceptance_tests # workaround for 'relative position not supported'
-            ./tests/test_manager.py -p./cudacpp_acceptance_tests/ test_simd_cpp_heft_ggh_double 
+            # *** NB1: acceptance tests require code generation (so in principle both PLUGIN and ../MG5aMC_PLUGIN are an option) 
+            # *** NB2: test_manager.py cannot handle absolute paths and '..' relative paths (therefore ../MG5aMC_PLUGIN will not work)
+            # *** ===> therefore, the only option is to install CUDACPP_OUTPUT in PLUGIN (this is done and undone in each CI job) 
+            if [ -f PLUGIN/CUDACPP_OUTPUT ]; then echo 'ERROR! PLUGIN/CUDACPP_OUTPUT already exists'; exit 1; fi
+            ln -sf ../../MG5aMC_PLUGIN/CUDACPP_OUTPUT PLUGIN/CUDACPP_OUTPUT
+            ./tests/test_manager.py -p./PLUGIN/CUDACPP_OUTPUT/acceptance_tests/ test_simd_cpp_heft_ggh_double 
+            rm -f PLUGIN/CUDACPP_OUTPUT
 
   simd_cpp_pptt_mixed:
     # The type of runner that the job will run on
@@ -93,9 +101,13 @@ jobs:
             cd MG5aMC/mg5amcnlo/
             cp input/.mg5_configuration_default.txt input/mg5_configuration.txt
             cp Template/LO/Source/.make_opts Template/LO/Source/make_opts
-            rm -f cudacpp_acceptance_tests
-            ln -sf ../MG5aMC_PLUGIN/CUDACPP_OUTPUT/acceptance_tests cudacpp_acceptance_tests # workaround for 'relative position not supported'
-            ./tests/test_manager.py -p./cudacpp_acceptance_tests/ test_simd_cpp_pptt_mixed 
+            # *** NB1: acceptance tests require code generation (so in principle both PLUGIN and ../MG5aMC_PLUGIN are an option) 
+            # *** NB2: test_manager.py cannot handle absolute paths and '..' relative paths (therefore ../MG5aMC_PLUGIN will not work)
+            # *** ===> therefore, the only option is to install CUDACPP_OUTPUT in PLUGIN (this is done and undone in each CI job) 
+            if [ -f PLUGIN/CUDACPP_OUTPUT ]; then echo 'ERROR! PLUGIN/CUDACPP_OUTPUT already exists'; exit 1; fi
+            ln -sf ../../MG5aMC_PLUGIN/CUDACPP_OUTPUT PLUGIN/CUDACPP_OUTPUT
+            ./tests/test_manager.py -p./PLUGIN/CUDACPP_OUTPUT/acceptance_tests/ test_simd_cpp_pptt_mixed 
+            rm -f PLUGIN/CUDACPP_OUTPUT
 
   simd_cpp_vector_size:
     # The type of runner that the job will run on
@@ -115,6 +127,10 @@ jobs:
             cd MG5aMC/mg5amcnlo/
             cp input/.mg5_configuration_default.txt input/mg5_configuration.txt
             cp Template/LO/Source/.make_opts Template/LO/Source/make_opts
-            rm -f cudacpp_acceptance_tests
-            ln -sf ../MG5aMC_PLUGIN/CUDACPP_OUTPUT/acceptance_tests cudacpp_acceptance_tests # workaround for 'relative position not supported'
-            ./tests/test_manager.py -p./cudacpp_acceptance_tests/ test_simd_cpp_vector_size 
+            # *** NB1: acceptance tests require code generation (so in principle both PLUGIN and ../MG5aMC_PLUGIN are an option) 
+            # *** NB2: test_manager.py cannot handle absolute paths and '..' relative paths (therefore ../MG5aMC_PLUGIN will not work)
+            # *** ===> therefore, the only option is to install CUDACPP_OUTPUT in PLUGIN (this is done and undone in each CI job) 
+            if [ -f PLUGIN/CUDACPP_OUTPUT ]; then echo 'ERROR! PLUGIN/CUDACPP_OUTPUT already exists'; exit 1; fi
+            ln -sf ../../MG5aMC_PLUGIN/CUDACPP_OUTPUT PLUGIN/CUDACPP_OUTPUT
+            ./tests/test_manager.py -p./PLUGIN/CUDACPP_OUTPUT/acceptance_tests/ test_simd_cpp_vector_size 
+            rm -f PLUGIN/CUDACPP_OUTPUT
