[install] modify and regenerate the acceptance tests after some cleanup

diff --git a/.github/workflows/madgraph_launch_test.yml b/.github/workflows/madgraph_launch_test.yml
--- a/.github/workflows/madgraph_launch_test.yml
+++ b/.github/workflows/madgraph_launch_test.yml
@@ -49,9 +49,10 @@ jobs:
             cd MG5aMC/mg5amcnlo/
             cp input/.mg5_configuration_default.txt input/mg5_configuration.txt
             cp Template/LO/Source/.make_opts Template/LO/Source/make_opts
-            rm -f cudacpp_acceptance_tests
-            ln -sf ../MG5aMC_PLUGIN/CUDACPP_OUTPUT/acceptance_tests cudacpp_acceptance_tests # workaround for 'relative position not supported'
-            ./tests/test_manager.py -p./cudacpp_acceptance_tests/ test_simd_cpp_eemumua_float 
+            if [ -f tests/cudacpp_acceptance_tests ]; then echo 'ERROR! tests/cudacpp_acceptance_tests already exists'; exit 1; fi # should never happen
+            ln -sf ../../MG5aMC_PLUGIN/CUDACPP_OUTPUT/acceptance_tests tests/cudacpp_acceptance_tests # workaround for 'relative position not supported'
+            ./tests/test_manager.py -p./tests/cudacpp_acceptance_tests/ test_simd_cpp_eemumua_float 
+            rm -f tests/cudacpp_acceptance_tests
 
   simd_cpp_heft_ggh_double:
     # The type of runner that the job will run on
@@ -71,9 +72,10 @@ jobs:
             cd MG5aMC/mg5amcnlo/
             cp input/.mg5_configuration_default.txt input/mg5_configuration.txt
             cp Template/LO/Source/.make_opts Template/LO/Source/make_opts
-            rm -f cudacpp_acceptance_tests
-            ln -sf ../MG5aMC_PLUGIN/CUDACPP_OUTPUT/acceptance_tests cudacpp_acceptance_tests # workaround for 'relative position not supported'
-            ./tests/test_manager.py -p./cudacpp_acceptance_tests/ test_simd_cpp_heft_ggh_double 
+            if [ -f tests/cudacpp_acceptance_tests ]; then echo 'ERROR! tests/cudacpp_acceptance_tests already exists'; exit 1; fi # should never happen
+            ln -sf ../../MG5aMC_PLUGIN/CUDACPP_OUTPUT/acceptance_tests tests/cudacpp_acceptance_tests # workaround for 'relative position not supported'
+            ./tests/test_manager.py -p./tests/cudacpp_acceptance_tests/ test_simd_cpp_heft_ggh_double 
+            rm -f tests/cudacpp_acceptance_tests
 
   simd_cpp_pptt_mixed:
     # The type of runner that the job will run on
@@ -93,9 +95,10 @@ jobs:
             cd MG5aMC/mg5amcnlo/
             cp input/.mg5_configuration_default.txt input/mg5_configuration.txt
             cp Template/LO/Source/.make_opts Template/LO/Source/make_opts
-            rm -f cudacpp_acceptance_tests
-            ln -sf ../MG5aMC_PLUGIN/CUDACPP_OUTPUT/acceptance_tests cudacpp_acceptance_tests # workaround for 'relative position not supported'
-            ./tests/test_manager.py -p./cudacpp_acceptance_tests/ test_simd_cpp_pptt_mixed 
+            if [ -f tests/cudacpp_acceptance_tests ]; then echo 'ERROR! tests/cudacpp_acceptance_tests already exists'; exit 1; fi # should never happen
+            ln -sf ../../MG5aMC_PLUGIN/CUDACPP_OUTPUT/acceptance_tests tests/cudacpp_acceptance_tests # workaround for 'relative position not supported'
+            ./tests/test_manager.py -p./tests/cudacpp_acceptance_tests/ test_simd_cpp_pptt_mixed 
+            rm -f tests/cudacpp_acceptance_tests
 
   simd_cpp_vector_size:
     # The type of runner that the job will run on
@@ -115,6 +118,7 @@ jobs:
             cd MG5aMC/mg5amcnlo/
             cp input/.mg5_configuration_default.txt input/mg5_configuration.txt
             cp Template/LO/Source/.make_opts Template/LO/Source/make_opts
-            rm -f cudacpp_acceptance_tests
-            ln -sf ../MG5aMC_PLUGIN/CUDACPP_OUTPUT/acceptance_tests cudacpp_acceptance_tests # workaround for 'relative position not supported'
-            ./tests/test_manager.py -p./cudacpp_acceptance_tests/ test_simd_cpp_vector_size 
+            if [ -f tests/cudacpp_acceptance_tests ]; then echo 'ERROR! tests/cudacpp_acceptance_tests already exists'; exit 1; fi # should never happen
+            ln -sf ../../MG5aMC_PLUGIN/CUDACPP_OUTPUT/acceptance_tests tests/cudacpp_acceptance_tests # workaround for 'relative position not supported'
+            ./tests/test_manager.py -p./tests/cudacpp_acceptance_tests/ test_simd_cpp_vector_size 
+            rm -f tests/cudacpp_acceptance_tests
